// 由上游目录生成的新增品牌展示信息。cards.ts 里已有的品牌不在此文件中。

import type { CardProduct } from "./cards"

export const generatedCardProducts: CardProduct[] = [
  {
    id: "rewarble",
    slug: "rewarble",
    name: "Rewarble 通用充值",
    shortName: "Rewarble",
    badge: "Topup",
    subtitle: "账户充值",
    description: "付款后获得兑换码。本站出售的是兑换码。",
    accent: "from-[#1d4ed8] via-[#3b82f6] to-[#93c5fd]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码。请到 rewarble.com/redeem 兑换，兑换时填写你的收款账户 ID，到账即为账户余额。请确认账户 ID 和币种无误，兑换后无法撤回。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "venmo",
    slug: "venmo",
    name: "Venmo 充值",
    shortName: "Venmo",
    badge: "Topup",
    subtitle: "账户充值",
    description: "付款后获得兑换码。本站出售的是兑换码。",
    accent: "from-[#0b5cd5] via-[#3d95ce] to-[#8ec5f0]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码。请到 rewarble.com/redeem 兑换，兑换时填写你的收款账户 ID，到账即为账户余额。请确认账户 ID 和币种无误，兑换后无法撤回。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "rewarble-revolut",
    slug: "rewarble-revolut",
    name: "Revolut 充值",
    shortName: "Revolut",
    badge: "Topup",
    subtitle: "账户充值",
    description: "付款后获得兑换码。本站出售的是兑换码。",
    accent: "from-[#0b0b0b] via-[#2b2b2b] to-[#5c5c5c]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码。请到 rewarble.com/redeem 兑换，兑换时填写你的收款账户 ID，到账即为账户余额。请确认账户 ID 和币种无误，兑换后无法撤回。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "rewarble-wise",
    slug: "rewarble-wise",
    name: "Wise 充值",
    shortName: "Wise",
    badge: "Topup",
    subtitle: "账户充值",
    description: "付款后获得兑换码。本站出售的是兑换码。",
    accent: "from-[#10b981] via-[#34d399] to-[#a7f3d0]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码。请到 rewarble.com/redeem 兑换，兑换时填写你的收款账户 ID，到账即为账户余额。请确认账户 ID 和币种无误，兑换后无法撤回。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "skrill",
    slug: "skrill",
    name: "Skrill 充值",
    shortName: "Skrill",
    badge: "Topup",
    subtitle: "账户充值",
    description: "付款后获得兑换码。本站出售的是兑换码。",
    accent: "from-[#6b1b7b] via-[#8e24aa] to-[#ce93d8]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码。请到 rewarble.com/redeem 兑换，兑换时填写你的收款账户 ID，到账即为账户余额。请确认账户 ID 和币种无误，兑换后无法撤回。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "rewarble-crypto",
    slug: "rewarble-crypto",
    name: "加密货币充值",
    shortName: "加密货币充值",
    badge: "Topup",
    subtitle: "账户充值",
    description: "付款后获得兑换码。本站出售的是兑换码。",
    accent: "from-[#0f172a] via-[#1e293b] to-[#475569]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码。请到 rewarble.com/redeem 兑换，兑换时填写你的收款账户 ID，到账即为账户余额。请确认账户 ID 和币种无误，兑换后无法撤回。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "advcash",
    slug: "advcash",
    name: "Advanced Cash 充值",
    shortName: "Advanced",
    badge: "Topup",
    subtitle: "账户充值",
    description: "付款后获得兑换码。本站出售的是兑换码。",
    accent: "from-[#065f46] via-[#0d9488] to-[#5eead4]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码。请到 rewarble.com/redeem 兑换，兑换时填写你的收款账户 ID，到账即为账户余额。请确认账户 ID 和币种无误，兑换后无法撤回。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "rewarble-luxon-pay",
    slug: "rewarble-luxon-pay",
    name: "Luxon Pay 充值",
    shortName: "Luxon",
    badge: "Topup",
    subtitle: "账户充值",
    description: "付款后获得兑换码。本站出售的是兑换码。",
    accent: "from-[#1e1b4b] via-[#4338ca] to-[#a5b4fc]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码。请到 rewarble.com/redeem 兑换，兑换时填写你的收款账户 ID，到账即为账户余额。请确认账户 ID 和币种无误，兑换后无法撤回。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "astropay",
    slug: "astropay",
    name: "AstroPay 充值",
    shortName: "AstroPay",
    badge: "Topup",
    subtitle: "账户充值",
    description: "付款后获得兑换码。本站出售的是兑换码。",
    accent: "from-[#064e3b] via-[#0f766e] to-[#5eead4]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码。请到 rewarble.com/redeem 兑换，兑换时填写你的收款账户 ID，到账即为账户余额。请确认账户 ID 和币种无误，兑换后无法撤回。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "volet",
    slug: "volet",
    name: "Volet 充值",
    shortName: "Volet",
    badge: "Topup",
    subtitle: "账户充值",
    description: "付款后获得兑换码。本站出售的是兑换码。",
    accent: "from-[#4d7c0f] via-[#84cc16] to-[#d9f99d]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码。请到 rewarble.com/redeem 兑换，兑换时填写你的收款账户 ID，到账即为账户余额。请确认账户 ID 和币种无误，兑换后无法撤回。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "payz",
    slug: "payz",
    name: "Payz 充值",
    shortName: "Payz",
    badge: "Topup",
    subtitle: "账户充值",
    description: "付款后获得兑换码。本站出售的是兑换码。",
    accent: "from-[#57534e] via-[#78716c] to-[#d6d3d1]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码。请到 rewarble.com/redeem 兑换，兑换时填写你的收款账户 ID，到账即为账户余额。请确认账户 ID 和币种无误，兑换后无法撤回。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "paysera",
    slug: "paysera",
    name: "Paysera 充值",
    shortName: "Paysera",
    badge: "Topup",
    subtitle: "账户充值",
    description: "付款后获得兑换码。本站出售的是兑换码。",
    accent: "from-[#1e3a8a] via-[#2563eb] to-[#93c5fd]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码。请到 rewarble.com/redeem 兑换，兑换时填写你的收款账户 ID，到账即为账户余额。请确认账户 ID 和币种无误，兑换后无法撤回。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "webmoney",
    slug: "webmoney",
    name: "WebMoney 充值",
    shortName: "WebMoney",
    badge: "Topup",
    subtitle: "账户充值",
    description: "付款后获得兑换码。本站出售的是兑换码。",
    accent: "from-[#0369a1] via-[#0ea5e9] to-[#bae6fd]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码。请到 rewarble.com/redeem 兑换，兑换时填写你的收款账户 ID，到账即为账户余额。请确认账户 ID 和币种无误，兑换后无法撤回。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "neteller",
    slug: "neteller",
    name: "Neteller 充值",
    shortName: "Neteller",
    badge: "Topup",
    subtitle: "账户充值",
    description: "付款后获得兑换码。本站出售的是兑换码。",
    accent: "from-[#14532d] via-[#16a34a] to-[#86efac]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码。请到 rewarble.com/redeem 兑换，兑换时填写你的收款账户 ID，到账即为账户余额。请确认账户 ID 和币种无误，兑换后无法撤回。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "rewarble-chatgpt",
    slug: "rewarble-chatgpt",
    name: "ChatGPT 虚拟卡",
    shortName: "ChatGPT",
    badge: "Card",
    subtitle: "Rewarble 虚拟卡",
    description: "付款后获得兑换码。本站出售的是兑换码，不是成品卡号。",
    accent: "from-[#064e3b] via-[#0f766e] to-[#5eead4]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码，不是成品卡号。请到 rewarble.com/redeem 兑换进钱包，再开一张虚拟卡。开卡费、充值费、月费与实名要求由 Rewarble 收取和判定，以兑换时页面为准。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "rewarble-midjourney",
    slug: "rewarble-midjourney",
    name: "Midjourney 虚拟卡",
    shortName: "Midjourney",
    badge: "Card",
    subtitle: "Rewarble 虚拟卡",
    description: "付款后获得兑换码。本站出售的是兑换码，不是成品卡号。",
    accent: "from-[#312e81] via-[#6366f1] to-[#c7d2fe]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码，不是成品卡号。请到 rewarble.com/redeem 兑换进钱包，再开一张虚拟卡。开卡费、充值费、月费与实名要求由 Rewarble 收取和判定，以兑换时页面为准。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "rewarble-temu",
    slug: "rewarble-temu",
    name: "Temu 虚拟卡",
    shortName: "Temu",
    badge: "Card",
    subtitle: "Rewarble 虚拟卡",
    description: "付款后获得兑换码。本站出售的是兑换码，不是成品卡号。",
    accent: "from-[#c2410c] via-[#f97316] to-[#fdba74]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码，不是成品卡号。请到 rewarble.com/redeem 兑换进钱包，再开一张虚拟卡。开卡费、充值费、月费与实名要求由 Rewarble 收取和判定，以兑换时页面为准。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "rewarble-aliexpress",
    slug: "rewarble-aliexpress",
    name: "AliExpress 虚拟卡",
    shortName: "AliExpress",
    badge: "Card",
    subtitle: "Rewarble 虚拟卡",
    description: "付款后获得兑换码。本站出售的是兑换码，不是成品卡号。",
    accent: "from-[#9a3412] via-[#ea580c] to-[#fed7aa]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码，不是成品卡号。请到 rewarble.com/redeem 兑换进钱包，再开一张虚拟卡。开卡费、充值费、月费与实名要求由 Rewarble 收取和判定，以兑换时页面为准。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "rewarble-facebook-ads",
    slug: "rewarble-facebook-ads",
    name: "Facebook Ads 虚拟卡",
    shortName: "Facebook",
    badge: "Card",
    subtitle: "Rewarble 虚拟卡",
    description: "付款后获得兑换码。本站出售的是兑换码，不是成品卡号。",
    accent: "from-[#1e3a8a] via-[#1877f2] to-[#93c5fd]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码，不是成品卡号。请到 rewarble.com/redeem 兑换进钱包，再开一张虚拟卡。开卡费、充值费、月费与实名要求由 Rewarble 收取和判定，以兑换时页面为准。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "rewarble-discord",
    slug: "rewarble-discord",
    name: "Discord 虚拟卡",
    shortName: "Discord",
    badge: "Card",
    subtitle: "Rewarble 虚拟卡",
    description: "付款后获得兑换码。本站出售的是兑换码，不是成品卡号。",
    accent: "from-[#3730a3] via-[#5865f2] to-[#c7d2fe]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码，不是成品卡号。请到 rewarble.com/redeem 兑换进钱包，再开一张虚拟卡。开卡费、充值费、月费与实名要求由 Rewarble 收取和判定，以兑换时页面为准。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "rewarble-fiverr",
    slug: "rewarble-fiverr",
    name: "Fiverr 虚拟卡",
    shortName: "Fiverr",
    badge: "Card",
    subtitle: "Rewarble 虚拟卡",
    description: "付款后获得兑换码。本站出售的是兑换码，不是成品卡号。",
    accent: "from-[#064e3b] via-[#1dbf73] to-[#86efac]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码，不是成品卡号。请到 rewarble.com/redeem 兑换进钱包，再开一张虚拟卡。开卡费、充值费、月费与实名要求由 Rewarble 收取和判定，以兑换时页面为准。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "rewarble-buymeacoffee",
    slug: "rewarble-buymeacoffee",
    name: "Buy Me a Coffee 虚拟卡",
    shortName: "Buy",
    badge: "Card",
    subtitle: "Rewarble 虚拟卡",
    description: "付款后获得兑换码。本站出售的是兑换码，不是成品卡号。",
    accent: "from-[#78350f] via-[#b45309] to-[#fcd34d]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码，不是成品卡号。请到 rewarble.com/redeem 兑换进钱包，再开一张虚拟卡。开卡费、充值费、月费与实名要求由 Rewarble 收取和判定，以兑换时页面为准。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "rewarble-patreon",
    slug: "rewarble-patreon",
    name: "Patreon 虚拟卡",
    shortName: "Patreon",
    badge: "Card",
    subtitle: "Rewarble 虚拟卡",
    description: "付款后获得兑换码。本站出售的是兑换码，不是成品卡号。",
    accent: "from-[#1c1917] via-[#44403c] to-[#a8a29e]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "本站出售的是兑换码，不是成品卡号。请到 rewarble.com/redeem 兑换进钱包，再开一张虚拟卡。开卡费、充值费、月费与实名要求由 Rewarble 收取和判定，以兑换时页面为准。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "playstation",
    slug: "playstation",
    name: "PlayStation",
    shortName: "PlayStation",
    badge: "Game",
    subtitle: "游戏点数",
    description: "付款后获得兑换码。游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。",
    accent: "from-[#003087] via-[#0070d1] to-[#7dd3fc]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。买错无法退换。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "blizzard",
    slug: "blizzard",
    name: "Blizzard",
    shortName: "Blizzard",
    badge: "Game",
    subtitle: "游戏点数",
    description: "付款后获得兑换码。游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。",
    accent: "from-[#0f172a] via-[#1e40af] to-[#93c5fd]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。买错无法退换。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "freefire",
    slug: "freefire",
    name: "Free Fire",
    shortName: "Free",
    badge: "Game",
    subtitle: "游戏点数",
    description: "付款后获得兑换码。游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。",
    accent: "from-[#7c2d12] via-[#ea580c] to-[#fdba74]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。买错无法退换。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "pubg",
    slug: "pubg",
    name: "PUBG",
    shortName: "PUBG",
    badge: "Game",
    subtitle: "游戏点数",
    description: "付款后获得兑换码。游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。",
    accent: "from-[#422006] via-[#a16207] to-[#fde68a]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。买错无法退换。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "riot-games",
    slug: "riot-games",
    name: "Riot Games",
    shortName: "Riot",
    badge: "Game",
    subtitle: "游戏点数",
    description: "付款后获得兑换码。游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。",
    accent: "from-[#7f1d1d] via-[#d13639] to-[#fca5a5]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。买错无法退换。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "mobile-legends",
    slug: "mobile-legends",
    name: "Mobile Legends",
    shortName: "Mobile",
    badge: "Game",
    subtitle: "游戏点数",
    description: "付款后获得兑换码。游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。",
    accent: "from-[#1e1b4b] via-[#4f46e5] to-[#a5b4fc]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。买错无法退换。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "fortnite",
    slug: "fortnite",
    name: "Fortnite",
    shortName: "Fortnite",
    badge: "Game",
    subtitle: "游戏点数",
    description: "付款后获得兑换码。游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。",
    accent: "from-[#1e1b4b] via-[#6d28d9] to-[#c4b5fd]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。买错无法退换。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "world-of-warcraft",
    slug: "world-of-warcraft",
    name: "魔兽世界",
    shortName: "魔兽世界",
    badge: "Game",
    subtitle: "游戏点数",
    description: "付款后获得兑换码。游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。",
    accent: "from-[#422006] via-[#b45309] to-[#fcd34d]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。买错无法退换。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "ea",
    slug: "ea",
    name: "EA",
    shortName: "EA",
    badge: "Game",
    subtitle: "游戏点数",
    description: "付款后获得兑换码。游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。",
    accent: "from-[#1c1917] via-[#dc2626] to-[#fca5a5]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。买错无法退换。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "nexon",
    slug: "nexon",
    name: "Nexon",
    shortName: "Nexon",
    badge: "Game",
    subtitle: "游戏点数",
    description: "付款后获得兑换码。游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。",
    accent: "from-[#172554] via-[#2563eb] to-[#93c5fd]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。买错无法退换。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "imvu",
    slug: "imvu",
    name: "IMVU",
    shortName: "IMVU",
    badge: "Game",
    subtitle: "游戏点数",
    description: "付款后获得兑换码。游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。",
    accent: "from-[#4a044e] via-[#a21caf] to-[#f0abfc]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "游戏平台的点数码通常按币种或地区锁定，请确认与你的账户一致后再购买。买错无法退换。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "netflix",
    slug: "netflix",
    name: "Netflix",
    shortName: "Netflix",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#450a0a] via-[#e50914] to-[#fca5a5]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "disney",
    slug: "disney",
    name: "Disney+",
    shortName: "Disney+",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#0f172a] via-[#1e40af] to-[#93c5fd]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "razer",
    slug: "razer",
    name: "Razer Gold",
    shortName: "Razer",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#14532d] via-[#44d62c] to-[#bbf7d0]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "twitch",
    slug: "twitch",
    name: "Twitch",
    shortName: "Twitch",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#4c1d95] via-[#9146ff] to-[#ddd6fe]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "uber",
    slug: "uber",
    name: "Uber & Uber Eats",
    shortName: "Uber",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#0f0f0f] via-[#2d2d2d] to-[#6b7280]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "airbnb",
    slug: "airbnb",
    name: "Airbnb",
    shortName: "Airbnb",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#7f1d1d] via-[#ff5a5f] to-[#fecaca]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "walmart",
    slug: "walmart",
    name: "Walmart",
    shortName: "Walmart",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#1e3a8a] via-[#0071ce] to-[#93c5fd]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "target",
    slug: "target",
    name: "Target",
    shortName: "Target",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#7f1d1d] via-[#cc0000] to-[#fca5a5]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "etsy",
    slug: "etsy",
    name: "Etsy",
    shortName: "Etsy",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#9a3412] via-[#f56400] to-[#fdba74]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "zalando",
    slug: "zalando",
    name: "Zalando",
    shortName: "Zalando",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#1c1917] via-[#44403c] to-[#d6d3d1]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "sephora",
    slug: "sephora",
    name: "Sephora",
    shortName: "Sephora",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#0a0a0a] via-[#262626] to-[#737373]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "douglas",
    slug: "douglas",
    name: "Douglas",
    shortName: "Douglas",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#1c1917] via-[#44403c] to-[#a8a29e]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "eneba",
    slug: "eneba",
    name: "Eneba",
    shortName: "Eneba",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#1e1b4b] via-[#4f46e5] to-[#a5b4fc]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "bol-com",
    slug: "bol-com",
    name: "Bol.com",
    shortName: "Bol.com",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#0369a1] via-[#0ea5e9] to-[#bae6fd]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "doordash",
    slug: "doordash",
    name: "DoorDash",
    shortName: "DoorDash",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#7f1d1d] via-[#ff3008] to-[#fecaca]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "justeat",
    slug: "justeat",
    name: "Just Eat",
    shortName: "Just",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#9a3412] via-[#ff8000] to-[#fed7aa]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "deliveroo",
    slug: "deliveroo",
    name: "Deliveroo",
    shortName: "Deliveroo",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#0f766e] via-[#00ccbc] to-[#99f6e4]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "takeaway",
    slug: "takeaway",
    name: "Takeaway.com",
    shortName: "Takeaway.com",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#9a3412] via-[#ff8000] to-[#fed7aa]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "lieferando",
    slug: "lieferando",
    name: "Lieferando",
    shortName: "Lieferando",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#9a3412] via-[#ff8000] to-[#fed7aa]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
  {
    id: "thuisbezorgd",
    slug: "thuisbezorgd",
    name: "Thuisbezorgd.nl",
    shortName: "Thuisbezorgd.nl",
    badge: "Gift Card",
    subtitle: "礼品卡",
    description: "付款后获得兑换码。请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。",
    accent: "from-[#9a3412] via-[#ff8000] to-[#fed7aa]",
    image: "",
    deliveryText: "付款后本页出现兑换入口，点进去复制兑换码",
    features: ["实时进价结算人民币", "付款后点兑换入口取码", "兑换码不发邮件，请当场保存"],
    purchaseNote: "请选择与你账户所在国家或地区一致的面额，跨区一般无法兑换。新注册或无消费记录的账户可能被品牌方风控要求补充购买凭证，建议使用有消费记录的老账户。",
    supportsSubscription: false,
    purchaseRule: { requiresCountrySelection: false, countries: [] },
  },
]
