export type CardProduct = {
  id: string
  slug: string
  name: string
  shortName: string
  badge: string
  subtitle: string
  description: string
  accent: string
  image: string
  deliveryText: string
  features: string[]
  purchaseNote: string
  supportsSubscription: boolean
}

export const cardProducts: CardProduct[] = [
  {
    id: "visa",
    slug: "visa",
    name: "Visa",
    shortName: "Visa",
    badge: "全球可用",
    subtitle: "虚拟 Visa 卡",
    description:
      "用户输入需要购买的美元面额后，系统会自动加上 2.5 USD 服务费，再按实时汇率换算为人民币支付。",
    accent: "from-[#0f3fb3] via-[#1c60f2] to-[#66a1ff]",
    image: "/visa-10.svg",
    deliveryText: "邮箱直发卡号 / 卡密 / 二维码",
    features: ["用户自填美元面额", "一次性消费", "不支持软件订阅"],
    purchaseNote: "Visa 卡仅支持一次性消费，不支持软件订阅。",
    supportsSubscription: false,
  },
  {
    id: "mastercard",
    slug: "mastercard",
    name: "Mastercard",
    shortName: "Mastercard",
    badge: "海外支付",
    subtitle: "虚拟 Mastercard 卡",
    description:
      "用户输入需要购买的美元面额后，系统会自动加上 2.5 USD 服务费，再按实时汇率换算为人民币支付。",
    accent: "from-[#111111] via-[#2d2d2d] to-[#575757]",
    image: "/mastercard-modern-design-.svg",
    deliveryText: "邮箱直发卡号 / 卡密 / 二维码",
    features: ["用户自填美元面额", "一次性消费", "不支持软件订阅"],
    purchaseNote: "Mastercard 卡仅支持一次性消费，不支持软件订阅。",
    supportsSubscription: false,
  },
  {
    id: "apple-gift-card",
    slug: "apple-gift-card",
    name: "Apple Gift Card",
    shortName: "Apple",
    badge: "礼品卡",
    subtitle: "Apple 礼品卡",
    description:
      "用户输入需要购买的美元面额后，系统会自动加上 2.5 USD 服务费，再按实时汇率换算为人民币支付。",
    accent: "from-[#111827] via-[#374151] to-[#9ca3af]",
    image: "/apple-pay-3.svg",
    deliveryText: "邮箱直发礼品卡卡密",
    features: ["用户自填美元面额", "邮箱发货", "不支持软件订阅"],
    purchaseNote: "Apple 礼品卡付款后会直接发送卡密到邮箱。",
    supportsSubscription: false,
  },
  {
    id: "google-play",
    slug: "google-play",
    name: "Google Gift Card",
    shortName: "Google",
    badge: "礼品卡",
    subtitle: "Google Play 礼品卡",
    description:
      "用户输入需要购买的美元面额后，系统会自动加上 2.5 USD 服务费，再按实时汇率换算为人民币支付。",
    accent: "from-[#14532d] via-[#16a34a] to-[#86efac]",
    image: "/google-pay-2.svg",
    deliveryText: "邮箱直发礼品卡卡密",
    features: ["用户自填美元面额", "邮箱发货", "不支持软件订阅"],
    purchaseNote: "Google Play 礼品卡付款后会直接发送卡密到邮箱。",
    supportsSubscription: false,
  },
  {
    id: "xbox",
    slug: "xbox",
    name: "Xbox Gift Card",
    shortName: "Xbox",
    badge: "礼品卡",
    subtitle: "Xbox 礼品卡",
    description: "适合 Xbox 相关礼品卡购买，付款后按邮箱发货。",
    accent: "from-[#0f5132] via-[#1b7f43] to-[#7ddc5f]",
    image: "/xbox-one-2.svg",
    deliveryText: "邮箱直发礼品卡卡密",
    features: ["礼品卡卡密发货", "邮箱接收", "后续可单独配置规则"],
    purchaseNote: "Xbox 礼品卡页面可继续补充更细的购买规则。",
    supportsSubscription: false,
  },
  {
    id: "amazon",
    slug: "amazon",
    name: "Amazon Gift Card",
    shortName: "Amazon",
    badge: "礼品卡",
    subtitle: "Amazon 礼品卡",
    description: "适合 Amazon 礼品卡购买，付款后按邮箱发货。",
    accent: "from-[#111827] via-[#1f2937] to-[#f59e0b]",
    image: "/amazon-pay-1.svg",
    deliveryText: "邮箱直发礼品卡卡密",
    features: ["礼品卡卡密发货", "邮箱接收", "后续可单独配置规则"],
    purchaseNote: "Amazon 礼品卡页面可继续补充更细的购买规则。",
    supportsSubscription: false,
  },
  {
    id: "ebay",
    slug: "ebay",
    name: "eBay Gift Card",
    shortName: "eBay",
    badge: "礼品卡",
    subtitle: "eBay 礼品卡",
    description: "适合 eBay 礼品卡购买，付款后按邮箱发货。",
    accent: "from-[#fbbf24] via-[#ef4444] to-[#2563eb]",
    image: "/ebay-1.svg",
    deliveryText: "邮箱直发礼品卡卡密",
    features: ["礼品卡卡密发货", "邮箱接收", "后续可单独配置规则"],
    purchaseNote: "eBay 礼品卡页面可继续补充更细的购买规则。",
    supportsSubscription: false,
  },
  {
    id: "nintendo",
    slug: "nintendo",
    name: "Nintendo Gift Card",
    shortName: "Nintendo",
    badge: "礼品卡",
    subtitle: "Nintendo 礼品卡",
    description: "适合 Nintendo 礼品卡购买，付款后按邮箱发货。",
    accent: "from-[#991b1b] via-[#dc2626] to-[#fb7185]",
    image: "/nintendo-switch-1.svg",
    deliveryText: "邮箱直发礼品卡卡密",
    features: ["礼品卡卡密发货", "邮箱接收", "后续可单独配置规则"],
    purchaseNote: "Nintendo 礼品卡页面可继续补充更细的购买规则。",
    supportsSubscription: false,
  },
  {
    id: "paypal",
    slug: "paypal",
    name: "PayPal",
    shortName: "PayPal",
    badge: "支付卡",
    subtitle: "PayPal 相关卡片",
    description: "适合 PayPal 相关卡片购买，后续可根据业务补充规则。",
    accent: "from-[#003087] via-[#0070ba] to-[#00a1e0]",
    image: "/paypal-4.svg",
    deliveryText: "邮箱直发卡号 / 卡密 / 二维码",
    features: ["邮箱接收", "后续可单独配置规则", "支持独立详情页扩展"],
    purchaseNote: "PayPal 页面可继续补充更细的购买规则。",
    supportsSubscription: false,
  },
  {
    id: "playstation",
    slug: "playstation",
    name: "PlayStation Gift Card",
    shortName: "PlayStation",
    badge: "礼品卡",
    subtitle: "PlayStation 礼品卡",
    description: "适合 PlayStation 礼品卡购买，付款后按邮箱发货。",
    accent: "from-[#0f172a] via-[#1d4ed8] to-[#60a5fa]",
    image: "/playstation-logo-and-wordmark.svg",
    deliveryText: "邮箱直发礼品卡卡密",
    features: ["礼品卡卡密发货", "邮箱接收", "后续可单独配置规则"],
    purchaseNote: "PlayStation 礼品卡页面可继续补充更细的购买规则。",
    supportsSubscription: false,
  },
  {
    id: "roblox",
    slug: "roblox",
    name: "Roblox Gift Card",
    shortName: "Roblox",
    badge: "礼品卡",
    subtitle: "Roblox 礼品卡",
    description: "适合 Roblox 礼品卡购买，付款后按邮箱发货。",
    accent: "from-[#111111] via-[#3f3f46] to-[#a1a1aa]",
    image: "/roblox-10.svg",
    deliveryText: "邮箱直发礼品卡卡密",
    features: ["礼品卡卡密发货", "邮箱接收", "后续可单独配置规则"],
    purchaseNote: "Roblox 礼品卡页面可继续补充更细的购买规则。",
    supportsSubscription: false,
  },
  {
    id: "spotify",
    slug: "spotify",
    name: "Spotify Gift Card",
    shortName: "Spotify",
    badge: "礼品卡",
    subtitle: "Spotify 礼品卡",
    description: "适合 Spotify 礼品卡购买，付款后按邮箱发货。",
    accent: "from-[#052e16] via-[#15803d] to-[#4ade80]",
    image: "/spotify-logo-with-text-1.svg",
    deliveryText: "邮箱直发礼品卡卡密",
    features: ["礼品卡卡密发货", "邮箱接收", "后续可单独配置规则"],
    purchaseNote: "Spotify 礼品卡页面可继续补充更细的购买规则。",
    supportsSubscription: false,
  },
  {
    id: "steam",
    slug: "steam",
    name: "Steam Gift Card",
    shortName: "Steam",
    badge: "礼品卡",
    subtitle: "Steam 礼品卡",
    description: "适合 Steam 礼品卡购买，付款后按邮箱发货。",
    accent: "from-[#0f172a] via-[#1e3a8a] to-[#0ea5e9]",
    image: "/steam-icon-logo.svg",
    deliveryText: "邮箱直发礼品卡卡密",
    features: ["礼品卡卡密发货", "邮箱接收", "后续可单独配置规则"],
    purchaseNote: "Steam 礼品卡页面可继续补充更细的购买规则。",
    supportsSubscription: false,
  },
]

export function getCardProductBySlug(slug: string) {
  return cardProducts.find((product) => product.slug === slug)
}
