// 本文件由上游目录生成。
// id = 站内标识（页面地址与接口参数，已上线的不可改动）
// brandSlug = 上游 Relograde 的品牌 slug
// 已上线并验证过出码的 5 个品牌配置为锁定值，改动前后完全一致。

export type RelogradeBrandMeta = {
  id: string
  brandSlug: string
  name: string
  pricingKind: "paymentcard" | "giftcard"
  groupedByRegion: boolean
  currencies: readonly string[]
  paymentCurrencyDefault: string
  showRewarbleFees: boolean
  redeemType: string
  colors: readonly [string, string, string]
}

export const RELOGRADE_BRAND_LIST: RelogradeBrandMeta[] = [
  {
    id: "steam",
    brandSlug: "steam",
    name: "Steam 钱包",
    pricingKind: "giftcard",
    groupedByRegion: false,
    currencies: ["USD", "EUR", "GBP", "SGD", "HKD", "TWD", "THB", "PHP", "MYR", "INR", "VND", "PLN"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#0f172a", "#1e3a8a", "#0ea5e9"],
  },
  {
    id: "rewarble",
    brandSlug: "rewarble",
    name: "Rewarble 通用充值",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["AUD", "CAD", "EUR", "GBP", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#1d4ed8", "#3b82f6", "#93c5fd"],
  },
  {
    id: "paypal",
    brandSlug: "paypal",
    name: "PayPal 充值",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["AUD", "CAD", "EUR", "GBP", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#003087", "#0070ba", "#5bb7ea"],
  },
  {
    id: "amazon",
    brandSlug: "amazon",
    name: "Amazon 礼品卡",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "service",
    colors: ["#0f172a", "#232f3e", "#ff9900"],
  },
  {
    id: "venmo",
    brandSlug: "venmo",
    name: "Venmo 充值",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#0b5cd5", "#3d95ce", "#8ec5f0"],
  },
  {
    id: "rewarble-revolut",
    brandSlug: "rewarble-revolut",
    name: "Revolut 充值",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["AUD", "CAD", "EUR", "GBP", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#0b0b0b", "#2b2b2b", "#5c5c5c"],
  },
  {
    id: "visa",
    brandSlug: "rewarble-visa",
    name: "Visa 虚拟卡",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: true,
    redeemType: "currency",
    colors: ["#0f3fb3", "#1c60f2", "#66a1ff"],
  },
  {
    id: "rewarble-wise",
    brandSlug: "rewarble-wise",
    name: "Wise 充值",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["AUD", "CAD", "EUR", "GBP", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#10b981", "#34d399", "#a7f3d0"],
  },
  {
    id: "skrill",
    brandSlug: "skrill",
    name: "Skrill 充值",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["EUR"],
    paymentCurrencyDefault: "EUR",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#6b1b7b", "#8e24aa", "#ce93d8"],
  },
  {
    id: "rewarble-crypto",
    brandSlug: "rewarble-crypto",
    name: "加密货币充值",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["AUD", "CAD", "EUR", "GBP", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#0f172a", "#1e293b", "#475569"],
  },
  {
    id: "advcash",
    brandSlug: "advcash",
    name: "Advanced Cash 充值",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["EUR", "GBP", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#065f46", "#0d9488", "#5eead4"],
  },
  {
    id: "rewarble-luxon-pay",
    brandSlug: "rewarble-luxon-pay",
    name: "Luxon Pay 充值",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["EUR", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#1e1b4b", "#4338ca", "#a5b4fc"],
  },
  {
    id: "astropay",
    brandSlug: "astropay",
    name: "AstroPay 充值",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["EUR", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#064e3b", "#0f766e", "#5eead4"],
  },
  {
    id: "volet",
    brandSlug: "volet",
    name: "Volet 充值",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["EUR", "GBP", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#4d7c0f", "#84cc16", "#d9f99d"],
  },
  {
    id: "payz",
    brandSlug: "payz",
    name: "Payz 充值",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["EUR", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#57534e", "#78716c", "#d6d3d1"],
  },
  {
    id: "paysera",
    brandSlug: "paysera",
    name: "Paysera 充值",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["EUR", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#1e3a8a", "#2563eb", "#93c5fd"],
  },
  {
    id: "webmoney",
    brandSlug: "webmoney",
    name: "WebMoney 充值",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#0369a1", "#0ea5e9", "#bae6fd"],
  },
  {
    id: "neteller",
    brandSlug: "neteller",
    name: "Neteller 充值",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["EUR"],
    paymentCurrencyDefault: "EUR",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#14532d", "#16a34a", "#86efac"],
  },
  {
    id: "mastercard",
    brandSlug: "rewarble-mastercard",
    name: "Mastercard 虚拟卡",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["USD", "EUR"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: true,
    redeemType: "currency",
    colors: ["#111111", "#2d2d2d", "#575757"],
  },
  {
    id: "rewarble-chatgpt",
    brandSlug: "rewarble-chatgpt",
    name: "ChatGPT 虚拟卡",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#064e3b", "#0f766e", "#5eead4"],
  },
  {
    id: "rewarble-midjourney",
    brandSlug: "rewarble-midjourney",
    name: "Midjourney 虚拟卡",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#312e81", "#6366f1", "#c7d2fe"],
  },
  {
    id: "rewarble-temu",
    brandSlug: "rewarble-temu",
    name: "Temu 虚拟卡",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#c2410c", "#f97316", "#fdba74"],
  },
  {
    id: "rewarble-aliexpress",
    brandSlug: "rewarble-aliexpress",
    name: "AliExpress 虚拟卡",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["EUR", "GBP", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#9a3412", "#ea580c", "#fed7aa"],
  },
  {
    id: "rewarble-facebook-ads",
    brandSlug: "rewarble-facebook-ads",
    name: "Facebook Ads 虚拟卡",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#1e3a8a", "#1877f2", "#93c5fd"],
  },
  {
    id: "rewarble-discord",
    brandSlug: "rewarble-discord",
    name: "Discord 虚拟卡",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#3730a3", "#5865f2", "#c7d2fe"],
  },
  {
    id: "rewarble-fiverr",
    brandSlug: "rewarble-fiverr",
    name: "Fiverr 虚拟卡",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#064e3b", "#1dbf73", "#86efac"],
  },
  {
    id: "rewarble-buymeacoffee",
    brandSlug: "rewarble-buymeacoffee",
    name: "Buy Me a Coffee 虚拟卡",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#78350f", "#b45309", "#fcd34d"],
  },
  {
    id: "rewarble-patreon",
    brandSlug: "rewarble-patreon",
    name: "Patreon 虚拟卡",
    pricingKind: "paymentcard",
    groupedByRegion: false,
    currencies: ["USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#1c1917", "#44403c", "#a8a29e"],
  },
  {
    id: "playstation",
    brandSlug: "playstation",
    name: "PlayStation",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#003087", "#0070d1", "#7dd3fc"],
  },
  {
    id: "xbox",
    brandSlug: "xbox",
    name: "Xbox",
    pricingKind: "giftcard",
    groupedByRegion: false,
    currencies: ["CAD", "EUR", "GBP", "SAR", "TRY", "USD", "ZAR"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#064e3b", "#107c10", "#86efac"],
  },
  {
    id: "nintendo",
    brandSlug: "nintendo",
    name: "Nintendo",
    pricingKind: "giftcard",
    groupedByRegion: false,
    currencies: ["CAD", "EUR", "GBP", "PLN", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#991b1b", "#e60012", "#fca5a5"],
  },
  {
    id: "blizzard",
    brandSlug: "blizzard",
    name: "Blizzard",
    pricingKind: "giftcard",
    groupedByRegion: false,
    currencies: ["EUR", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#0f172a", "#1e40af", "#93c5fd"],
  },
  {
    id: "roblox",
    brandSlug: "roblox",
    name: "Roblox",
    pricingKind: "giftcard",
    groupedByRegion: false,
    currencies: ["AUD", "BRL", "CAD", "EUR", "GBP", "MYR", "NZD", "PLN", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#1c1917", "#e2231a", "#fca5a5"],
  },
  {
    id: "freefire",
    brandSlug: "freefire",
    name: "Free Fire",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#7c2d12", "#ea580c", "#fdba74"],
  },
  {
    id: "pubg",
    brandSlug: "pubg",
    name: "PUBG",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#422006", "#a16207", "#fde68a"],
  },
  {
    id: "riot-games",
    brandSlug: "riot-games",
    name: "Riot Games",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#7f1d1d", "#d13639", "#fca5a5"],
  },
  {
    id: "mobile-legends",
    brandSlug: "mobile-legends",
    name: "Mobile Legends",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#1e1b4b", "#4f46e5", "#a5b4fc"],
  },
  {
    id: "fortnite",
    brandSlug: "fortnite",
    name: "Fortnite",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#1e1b4b", "#6d28d9", "#c4b5fd"],
  },
  {
    id: "world-of-warcraft",
    brandSlug: "world-of-warcraft",
    name: "魔兽世界",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "EUR",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#422006", "#b45309", "#fcd34d"],
  },
  {
    id: "ea",
    brandSlug: "ea",
    name: "EA",
    pricingKind: "giftcard",
    groupedByRegion: false,
    currencies: ["EUR", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#1c1917", "#dc2626", "#fca5a5"],
  },
  {
    id: "nexon",
    brandSlug: "nexon",
    name: "Nexon",
    pricingKind: "giftcard",
    groupedByRegion: false,
    currencies: ["AUD", "NZD"],
    paymentCurrencyDefault: "AUD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#172554", "#2563eb", "#93c5fd"],
  },
  {
    id: "imvu",
    brandSlug: "imvu",
    name: "IMVU",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#4a044e", "#a21caf", "#f0abfc"],
  },
  {
    id: "apple-gift-card",
    brandSlug: "apple",
    name: "Apple 礼品卡",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "EUR",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#111827", "#374151", "#9ca3af"],
  },
  {
    id: "google-play",
    brandSlug: "google",
    name: "Google Play 礼品卡",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "EUR",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#14532d", "#16a34a", "#86efac"],
  },
  {
    id: "netflix",
    brandSlug: "netflix",
    name: "Netflix",
    pricingKind: "giftcard",
    groupedByRegion: false,
    currencies: ["BRL", "EUR", "GBP", "SAR", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#450a0a", "#e50914", "#fca5a5"],
  },
  {
    id: "disney",
    brandSlug: "disney",
    name: "Disney+",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "EUR",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#0f172a", "#1e40af", "#93c5fd"],
  },
  {
    id: "razer",
    brandSlug: "razer",
    name: "Razer Gold",
    pricingKind: "giftcard",
    groupedByRegion: false,
    currencies: ["CZK", "DKK", "EUR", "NOK", "PLN", "RON", "SEK", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#14532d", "#44d62c", "#bbf7d0"],
  },
  {
    id: "twitch",
    brandSlug: "twitch",
    name: "Twitch",
    pricingKind: "giftcard",
    groupedByRegion: false,
    currencies: ["CAD", "EUR", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#4c1d95", "#9146ff", "#ddd6fe"],
  },
  {
    id: "uber",
    brandSlug: "uber",
    name: "Uber & Uber Eats",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "EUR",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#0f0f0f", "#2d2d2d", "#6b7280"],
  },
  {
    id: "airbnb",
    brandSlug: "airbnb",
    name: "Airbnb",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#7f1d1d", "#ff5a5f", "#fecaca"],
  },
  {
    id: "walmart",
    brandSlug: "walmart",
    name: "Walmart",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#1e3a8a", "#0071ce", "#93c5fd"],
  },
  {
    id: "target",
    brandSlug: "target",
    name: "Target",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#7f1d1d", "#cc0000", "#fca5a5"],
  },
  {
    id: "etsy",
    brandSlug: "etsy",
    name: "Etsy",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#9a3412", "#f56400", "#fdba74"],
  },
  {
    id: "zalando",
    brandSlug: "zalando",
    name: "Zalando",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "EUR",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#1c1917", "#44403c", "#d6d3d1"],
  },
  {
    id: "sephora",
    brandSlug: "sephora",
    name: "Sephora",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "CAD",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#0a0a0a", "#262626", "#737373"],
  },
  {
    id: "douglas",
    brandSlug: "douglas",
    name: "Douglas",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "EUR",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#1c1917", "#44403c", "#a8a29e"],
  },
  {
    id: "eneba",
    brandSlug: "eneba",
    name: "Eneba",
    pricingKind: "giftcard",
    groupedByRegion: false,
    currencies: ["EUR", "GBP", "USD"],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#1e1b4b", "#4f46e5", "#a5b4fc"],
  },
  {
    id: "bol-com",
    brandSlug: "bol-com",
    name: "Bol.com",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "EUR",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#0369a1", "#0ea5e9", "#bae6fd"],
  },
  {
    id: "doordash",
    brandSlug: "doordash",
    name: "DoorDash",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "USD",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#7f1d1d", "#ff3008", "#fecaca"],
  },
  {
    id: "justeat",
    brandSlug: "justeat",
    name: "Just Eat",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "EUR",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#9a3412", "#ff8000", "#fed7aa"],
  },
  {
    id: "deliveroo",
    brandSlug: "deliveroo",
    name: "Deliveroo",
    pricingKind: "giftcard",
    groupedByRegion: false,
    currencies: ["EUR", "GBP"],
    paymentCurrencyDefault: "EUR",
    showRewarbleFees: false,
    redeemType: "currency",
    colors: ["#0f766e", "#00ccbc", "#99f6e4"],
  },
  {
    id: "takeaway",
    brandSlug: "takeaway",
    name: "Takeaway.com",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "EUR",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#9a3412", "#ff8000", "#fed7aa"],
  },
  {
    id: "lieferando",
    brandSlug: "lieferando",
    name: "Lieferando",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "EUR",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#9a3412", "#ff8000", "#fed7aa"],
  },
  {
    id: "thuisbezorgd",
    brandSlug: "thuisbezorgd",
    name: "Thuisbezorgd.nl",
    pricingKind: "giftcard",
    groupedByRegion: true,
    currencies: [],
    paymentCurrencyDefault: "EUR",
    showRewarbleFees: false,
    redeemType: "region",
    colors: ["#9a3412", "#ff8000", "#fed7aa"],
  },
]

export const RELOGRADE_BRAND_MAP: Record<string, RelogradeBrandMeta> =
  RELOGRADE_BRAND_LIST.reduce<Record<string, RelogradeBrandMeta>>((acc, item) => {
    acc[item.id] = item
    return acc
  }, {})
